const goods = [
    {
        "availability": 1,  // 1 есть в наличии, 0 - нет в наличии
        "id": "tPR1Uhkp",
        "name": "Качотта",
        "titleDescription": "Традиційний італійський сир с визріванням та рожевою скоринкою.",
        "description": "Традиційний італійський сир с визріванням та рожевою скоринкою.",
        "price100": 40,
        "price300": 120,
        "totalPriceSelectedItem": 120,
        "productWeight": 300,
        "minProductWeight": 300,
        "amount": 1,
        "imgWebp": "./images/Products/cheese/Качотта.webp",
        "image": "./images/Products/cheese/Качотта.jpg",
        "preImg": "./images/Products/cheese/Качотта-s.jpg",
        "iconMinusStatus": "notActive",
        "totalAmountOfAllGoods": 120,
        "totalWeightOfAllGoods": 300
    },
    {
        "availability": 1,
        "id": "QhKmsMtF",
        "name": "Карачун",
        "titleDescription": "Авторський сир с визріванням та біло-рожевою скоринкою.",
        "description": "Карачун - це авторський сир нашого Сировара. Виготовлений з коров'ячого молока, має приємний ніжний вершковий смак.Термін дозрівання не менше одного місяця. Добре смакує з сухими винами.",
        "price100": 40,
        "price300": 120,
        "totalPriceSelectedItem": 120,
        "productWeight": 300,
        "minProductWeight": 300,
        "amount": 1,
        "imgWebp": "./images/Products/cheese/Карачун.webp",
        "image": "./images/Products/cheese/Карачун.jpg",
        "preImg": "./images/Products/cheese/Карачун-s.jpg",
        "iconMinusStatus": "notActive",
        "totalAmountOfAllGoods": 120,
        "totalWeightOfAllGoods": 300
    },
    {
        "availability": 1,
        "id": "6udUvSWE",
        "name": "Скіф",
        "titleDescription": "Традиційний французський сир с визріванням та рожевою скоринкою.",
        "description": "Традиційний французський сир с визріванням та рожевою скоринкою.",
        "price100": 40,
        "price300": 120,
        "totalPriceSelectedItem": 120,
        "productWeight": 300,
        "minProductWeight": 300,
        "amount": 1,
        "imgWebp": "./images/Products/cheese/Скіф.webp",
        "image": "./images/Products/cheese/Скіф.jpg",
        "preImg": "./images/Products/cheese/Скіф-s.jpg",
        "iconMinusStatus": "notActive",
        "totalAmountOfAllGoods": 120,
        "totalWeightOfAllGoods": 300
    },
    {
        "availability": 1,
        "id": "meTDfnZt",
        "name": "Реблошон",
        "titleDescription": "Традиційний французський сир с визріванням та біло-рожевою скоринкою.",
        "description": "Традиційний французський сир с визріванням та біло-рожевою скоринкою.",
        "price100": 40,
        "price300": 120,
        "totalPriceSelectedItem": 120,
        "productWeight": 300,
        "minProductWeight": 300,
        "amount": 1,
        "imgWebp": "./images/Products/cheese/Реблошон.webp",
        "image": "./images/Products/cheese/Реблошон.jpg",
        "preImg": "./images/Products/cheese/Реблошон-s.jpg",
        "iconMinusStatus": "notActive",
        "totalAmountOfAllGoods": 120,
        "totalWeightOfAllGoods": 300
    },
    {
        "availability": 1,
        "id": "i7yiatiB",
        "name": "Гауда",
        "titleDescription": "Традиційний голандський сир с визріванням.",
        "description": "Традиційний голандський сир с визріванням.",
        "price100": 45,
        "price300": 135,
        "totalPriceSelectedItem": 135,
        "productWeight": 300,
        "minProductWeight": 300,
        "amount": 1,
        "imgWebp": "./images/Products/cheese/Гауда.webp",
        "image": "./images/Products/cheese/Гауда.jpg",
        "preImg": "./images/Products/cheese/Гауда-s.jpg",
        "iconMinusStatus": "notActive",
        "totalAmountOfAllGoods": 120,
        "totalWeightOfAllGoods": 300
    },
    {
        "availability": 1,
        "id": "XLWj2q9V",
        "name": "Кайрфіллі",
        "titleDescription": "Традиційний англійський сир с визріванням.",
        "description": "Традиційний англійський сир с визріванням.",
        "price100": 40,
        "price300": 120,
        "totalPriceSelectedItem": 120,
        "productWeight": 300,
        "minProductWeight": 300,
        "amount": 1,
        "imgWebp": "./images/Products/cheese/Кайрфіллі.webp",
        "image": "./images/Products/cheese/Кайрфіллі.jpg",
        "preImg": "./images/Products/cheese/Кайрфіллі-s.jpg",
        "iconMinusStatus": "notActive",
        "totalAmountOfAllGoods": 120,
        "totalWeightOfAllGoods": 300
    },
    {
        "availability": 1,
        "id": "-o_AMdjH",
        "name": "Чеддер",
        "titleDescription": "Традиційний англійський сир с визріванням та бандажом.",
        "description": "Традиційний англійський сир с визріванням та бандажом.",
        "price100": 50,
        "price300": 150,
        "totalPriceSelectedItem": 150,
        "productWeight": 300,
        "minProductWeight": 300,
        "amount": 1,
        "imgWebp": "./images/Products/cheese/Чеддер.webp",
        "image": "./images/Products/cheese/Чеддер.jpg",
        "preImg": "./images/Products/cheese/Чеддер-s.jpg",
        "iconMinusStatus": "notActive",
        "totalAmountOfAllGoods": 120,
        "totalWeightOfAllGoods": 300
    },
    {
        "availability": 1,
        "id": "5syIO6QA",
        "name": "Монтеррей Джек",
        "titleDescription": "Традиційний амеріканський сир з папрікою с визріванням.",
        "description": "Традиційний амеріканський сир з папрікою с визріванням.",
        "price100": 45,
        "price300": 135,
        "totalPriceSelectedItem": 135,
        "productWeight": 300,
        "minProductWeight": 300,
        "amount": 1,
        "imgWebp": "./images/Products/cheese/Монтеррей_Джек.webp",
        "image": "./images/Products/cheese/Монтеррей Джек.jpg",
        "preImg": "./images/Products/cheese/Монтеррей Джек-s.jpg",
        "iconMinusStatus": "notActive",
        "totalAmountOfAllGoods": 120,
        "totalWeightOfAllGoods": 300
    },
    {
        "availability": 0,
        "id": "RzXbHILm",
        "name": "Торський сир",
        "titleDescription": "Свіжій ніжний молочний сир без визрівання (аналог Осетинського).",
        "description": "Свіжій ніжний молочний сир без визрівання (аналог Осетинського).",
        "price100": 30,
        "price300": 90,
        "totalPriceSelectedItem": 90,
        "productWeight": 300,
        "minProductWeight": 300,
        "amount": 1,
        "imgWebp": "./images/Products/cheese/Торський сир.webp",
        "image": "./images/Products/cheese/Торський сир.jpg",
        "preImg": "./images/Products/cheese/Торський сир-s.jpg",
        "iconMinusStatus": "notActive",
        "totalAmountOfAllGoods": 120,
        "totalWeightOfAllGoods": 300
    },
    {
        "availability": 0,
        "id": "4InYazF3",
        "name": "Маасдам",
        "titleDescription": "Традиційний голандський сир с визріванням.",
        "description": "Традиційний голандський сир с визріванням.",
        "price100": 45,
        "price300": 135,
        "totalPriceSelectedItem": 135,
        "productWeight": 300,
        "minProductWeight": 300,
        "amount": 1,
        "imgWebp": "./images/Products/cheese/Маасдам.webp",
        "image": "./images/Products/cheese/Маасдам.jpg",
        "preImg": "./images/Products/cheese/Маасдам-s.jpg",
        "iconMinusStatus": "notActive",
        "totalAmountOfAllGoods": 120,
        "totalWeightOfAllGoods": 300
    },
    {
        "availability": 0,
        "id": "F5S-S36-",
        "name": "Каммамбер",
        "titleDescription": "Традиційний французський сир с визріванням та білою скоринкою.",
        "description": "Традиційний французський сир с визріванням та білою скоринкою.",
        "price100": 40,
        "price300": 120,
        "totalPriceSelectedItem": 120,
        "productWeight": 300,
        "minProductWeight": 300,
        "amount": 1,
        "imgWebp": "./images/Products/cheese/Каммамбер.webp",
        "image": "./images/Products/cheese/Каммамбер.jpg",
        "preImg": "./images/Products/cheese/Каммамбер-s.jpg",
        "iconMinusStatus": "notActive",
        "totalAmountOfAllGoods": 120,
        "totalWeightOfAllGoods": 300
    },
    {
        "availability": 0,
        "id": "6vFscpA-",
        "name": "Люторс",
        "titleDescription": "Авторський сир за принципом каммамбера з білою скоринкою.",
        "description": "Авторський сир за принципом каммамбера з білою скоринкою.",
        "price100": 40,
        "price300": 120,
        "totalPriceSelectedItem": 120,
        "productWeight": 300,
        "minProductWeight": 300,
        "amount": 1,
        "imgWebp": "./images/Products/cheese/Люторс.webp",
        "image": "./images/Products/cheese/Люторс.jpg",
        "preImg": "./images/Products/cheese/Люторс-s.jpg",
        "iconMinusStatus": "iconActive",
        "totalAmountOfAllGoods": 120,
        "totalWeightOfAllGoods": 300
    }
];

export default goods;